jdk: oraclejdk8
language: java

sudo: false

install: true

script: mvn clean verify sonar:sonar -Dsonar.projectKey=com.github.cloudyrock.dimmer -Dsonar.organization=cloudyrock -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b3ad74729ae5d41a7248e50e686d44b755f3a092 -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=117 -Dsonar.pullrequest.branch=test_fork_analisys



# only triggering master
branches:
  only:
  - master
  - pr-integration

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
    secure: OvziLP5sI0f//jZNkBcCux0hzfwV2nqHEfYwx+qJwwTvfcaA7sfRjsd8GsxKlOugK1X5RCdPcHjGUTKOHyzsFOCrvGKaws2qFDOLLN+jKw0ggLyv7gO7bmzWnkqczalCP1B26QzEYMs77Q0xPWUWt3z2XVDuTAVcDZeuT51phhz2gFmMWxQ/zj65fOCfBssZmJrhdisJtDx5vF7alLXRhFqyIIiPNtRWgx7grpAo6rRYOHtxsYgasnQ9f2mmYhWDRv8wW8nmbwOD9xIY7NjA8qUW4O6LTb0OtQnKLoXLbiisgiPprmF3nUTCrs5UB6aRkKtOt+HzMyWkKZhLjjs6rjAoclnsqlsuVZK9oMQyhP7jmcFs6oc4OIJPQd7EIX18hsf22qztc6K2oVXi4r6LddFcVeINR5JA77fn0JKehosAXxbhKCZFomGMRa3PMuHaX+o4M5ISOYzUeE+H8DM7L6jMmIC5xoRQFkHkRFnJOfjS5Ln6+l88P5MqnP98gujvgVtdJT7M7Qsq0xKPSyAQDgtyNKrsg2nHmwz/F0Z8ooLcytzMTNh1SIw3M7/f5c7khQM5rDq4RXxrmyRWXUsmvESJHSztKRZ47Vy6V4BufTmVldKAKbmgoO4+d+ij/QS9VjdwSV9let4KD7rsqUIvB+kNZWKFzYXIbNgsLyQz2G0=
